name: CI/CD Pipeline
on:
  workflow_dispatch:

jobs:
  SonarCloud:
    uses: 
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploy-To-GKE:
    if: github.event_name == 'push'
    uses: 
    with:
        ARGO_APP: salesforce
    secrets: inherit
